version: 2.1
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: curl -sSL https://install.python-poetry.org | python -
      - run:
          name: Install dependencies via Makefile
          command: make install
      - run:
          name: Run tests and collect coverage via Makefile
          command: make coverage
      - codecov/upload

workflows:
  version: 2.1
  build-test:
    jobs:
      - build