name: flask-api

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies, assuming they are specified in your Makefile's 'install' target
      - run: make install

      # Generate documentation using a target from your Makefile
      - run: make doc  
      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/  

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
