name: flask-api-documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install Dependencies
        run: make install
      - run: make doc  
      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: docs/
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: documentation
          path: documentation
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          artifact_name: documentation